{
 "title": "recsys_app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "vRAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Processing Time, ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Default (offline) Recommendations Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "recommendation_default_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Personalized (offline) Recommendations Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "recommendation_personalized_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Similar Items (online) Recommendations Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "recommendation_i2i_requests_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}